name: Saludo usando variables y secretos
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
  SALUDO: Hola
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "${{ env.SALUDO }}, ${{ vars.NOMBRE }}. Hoy es ${{ env.DIA_DE_SEMANA }}!"
  saludo-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo secretos
        run: echo "${{ env.SALUDO }}, ${{ vars.NOMBRE }}. Tu contraseña es ${{ secrets.CONTRASENA }}!"
